language: C
dist: focal
sudo: true

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt build-dep dleyna-core
  - suda apt install clang-tools

jobs:
    include:
        - stage: build
          env: NOCONFIGURE=1
          script:
              - ./autogen.sh
              - mkdir build-plain
              - (cd build-plain && ./configure --enable-debug --disable-Werror)
              - make -C build-plain
        - stage: scan-build
          script:
              - mkdir build-scan
              - (cd build-scan && scan-build ./configure --enable-debug --disable-Werror)
              - scan-build make -C build-scan

